[project]
name = "Engine"
version = "v1.0.0"
description = "MalDec Labs engine for detect malwares and analysis deriveds formats files"
copyright = "@maldeclabs"

[yara]
malware_rules = "rules/yara/malwares"

[sig]
packeds_rules = "rules/signatures/packeds"

[log]
name = "logs/engine.log"
level = 1                # level default (spdlog::level::debug)
trace = 0                # update realtime log in file
type = "day"             # rotating, basic (default)
max_files = 100
# if type = 'day'
hours = 2
minutes = 30
# if type = 'rotating'
max_size = 1048576

[crow]
bindaddr = "127.0.0.1"
port = 8181
websocket_conn_whitelist = ["127.0.0.1"] # whitelist for connect engine websocket

[postgresql]
dbname = ""
hostaddr = "127.0.0.1"
port = 6123
password = ""
user = ""

[cache]
type = "day"       # rotating
name = "cache.db3"
# if type = 'rotating'
max_size = 1048576