[project]
name = "Engine"
version = "v1.0.0"
description = "MalDec Labs engine for detect malwares and analysis deriveds formats files"
copyright = "@maldeclabs"

[yara]
malware_rules = "rules/yara/malwares"
packeds_rules = "rules/yara/packeds"
cve_rules = "rules/yara/cve"

[clamav]
default_database = "rules/clamav/default"

[sig]
packeds_rules = "rules/signatures/packeds"

[log]
name = "logs/engine.log"
console = true
level = 1                # level default (spdlog::level::debug)
trace = 0                # update realtime log in file
type = "day"             # rotating, basic (default)
max_files = 100
hours = 2                # if type = 'day'
minutes = 30             # if type = 'day'
max_size = 10485       # if type = 'rotating'

[crowapp]
bindaddr = "127.0.0.1"
port = 8181
threads = 16 # minimum 2
context_whitelist = ["127.0.0.1"] # whitelist for connect engine websocket
ssl_file_pem = ""

[cache]
type = "day"       # rotating
name = "cache.db3"