[yara]
rules = "rules/yara"

[log]
name = "logs/engine.log"
level = 1
trace = 0
type = "day" # rotating, basic (default)
max_files = 100
# if type = 'day'
hours = 2
minutes = 30
# if type = 'rotating'
max_size = 1048576

[crow]
bindaddr = "127.0.0.1"
port = 8080
whitelist = ["127.0.0.1"]

[database]
dbname = ""
hostaddr = "127.0.0.1"
port = 6123
password = ""
user = ""