CREATE TABLE IF NOT EXISTS analysis (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    file_name VARCHAR(255) NOT NULL UNIQUE,
    file_type VARCHAR(100),
    file_size BIGINT,
    file_path TEXT,
    file_entropy DOUBLE PRECISION,
    mime_type VARCHAR(100),
    sha256 VARCHAR(64) UNIQUE,
    sha1 VARCHAR(40) UNIQUE,
    sha512 VARCHAR(128) UNIQUE,
    sha224 VARCHAR(56) UNIQUE,
    sha384 VARCHAR(96) UNIQUE,
    sha3_256 VARCHAR(64) UNIQUE,
    sha3_512 VARCHAR(128) UNIQUE,
    tlsh VARCHAR(255) UNIQUE,
    family_id INTEGER,
    description TEXT,
    creation_date VARCHAR(40) DEFAULT CURRENT_TIMESTAMP,
    last_update_date VARCHAR(40) DEFAULT CURRENT_TIMESTAMP,
    is_malicious BOOLEAN,
    is_packed BOOLEAN,
    owner VARCHAR(100),
    FOREIGN KEY (family_id) REFERENCES family(id) ON DELETE SET NULL
);