name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  checkout_and_build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do repositório principal
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Inclui os submódulos

      # Passo 2: Configurar chave SSH para o repositório principal e submódulos
      - name: Setup SSH for private repositories
        run: |
          mkdir -p ~/.ssh

          # Configurar chave SSH para o repositório principal
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host github.com\n  IdentityFile ~/.ssh/id_rsa\n" >> ~/.ssh/config

          # Configurar chave SSH para o submódulo 'lief'
          echo "${{ secrets.SSH_PRIVATE_KEY_LIEF }}" > ~/.ssh/id_rsa_lief
          chmod 600 ~/.ssh/id_rsa_lief
          echo -e "Host github.com-maldeclabs-lief\n  IdentityFile ~/.ssh/id_rsa_lief\n" >> ~/.ssh/config

          # Configurar chave SSH para o submódulo 'signatures'
          echo "${{ secrets.SSH_PRIVATE_KEY_SIGNATURES }}" > ~/.ssh/id_rsa_signatures
          chmod 600 ~/.ssh/id_rsa_signatures
          echo -e "Host github.com-maldeclabs-signatures\n  IdentityFile ~/.ssh/id_rsa_signatures\n" >> ~/.ssh/config

          # Adicionar GitHub ao arquivo known_hosts para evitar a pergunta sobre a chave do host
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      # Passo 3: Forçar o uso de SSH para os submódulos
      - name: Update Submodules with SSH
        run: |
          # Sincronizar submódulos para garantir que as URLs estejam corretas
          git submodule sync

          # Atualizar os submódulos para garantir que o SSH esteja sendo usado
          git submodule update --init --recursive

          # Forçar a URL do submódulo para usar SSH
          git submodule foreach '
            if [ "$name" == "libraries/lief" ]; then
              git remote set-url origin git@github.com:maldeclabs/lief.git;
            elif [ "$name" == "libraries/signatures" ]; then
              git remote set-url origin git@github.com:maldeclabs/signatures.git;
            fi
          '

      # Passo 4: Build e testes (exemplo)
      - name: Build Project
        run: |
          # Coloque o comando para compilar ou testar o seu projeto aqui
          make build

      # Passo 5: Exemplo de deploy ou outra ação
      - name: Deploy
        run: |
          # Coloque o comando de deploy ou outra ação que você precise aqui
          make deploy
