name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        if [ "${{ github.ref_name }}" = "main" ]; then
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/exoctl:${{ github.sha }}
        else
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/exoctl:dev-${{ github.sha }}
        fi

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        if [ "${{ github.ref_name }}" = "main" ]; then
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/exoctl:${{ github.sha }}
        else
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/exoctl:dev-${{ github.sha }}
        fi
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_PAT }}
    - name: Push the Docker image
      run: |
        if [ "${{ github.ref_name }}" = "main" ]; then
          docker push ghcr.io/${{ github.repository_owner }}/exoctl:${{ github.sha }}
        else
          docker push ghcr.io/${{ github.repository_owner }}/exoctl:dev-${{ github.sha }}
        fi