jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Configurar SSH para acessar reposit贸rios privados
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_KEY_SSH }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo -e "Host github.com\n  IdentityFile ~/.ssh/id_rsa\n" >> ~/.ssh/config
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    # Checkout do reposit贸rio com subm贸dulos
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
        ssh-keyscan: true

    # Atualizar subm贸dulos manualmente (opcional)
    - name: Update Submodules
      run: |
        git submodule sync
        git submodule update --init --recursive

    # Construir a imagem Docker
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag engine-skull:$(date +%s)
