name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        if [ "${{ github.ref_name }}" = "main" ]; then
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/exoctl:latest --tag ghcr.io/${{ github.repository_owner }}/exoctl:${{ github.sha }}
        else
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/exoctl:dev --tag ghcr.io/${{ github.repository_owner }}/exoctl:dev-${{ github.sha }}
        fi
    - name: Save Docker image as tarball
      run: |
        if [ "${{ github.ref_name }}" = "main" ]; then
          docker save -o exoctl-image.tar ghcr.io/${{ github.repository_owner }}/exoctl:latest
        else
          docker save -o exoctl-image.tar ghcr.io/${{ github.repository_owner }}/exoctl:dev
        fi
    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: exoctl-image
        path: exoctl-image.tar
        retention-days: 1

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Download Docker image artifact
      uses: actions/download-artifact@v4
      with:
        name: exoctl-image
        path: .
    - name: Load Docker image
      run: |
        docker load -i exoctl-image.tar
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_PAT }}
    - name: Push the Docker image
      run: |
        if [ "${{ github.ref_name }}" = "main" ]; then
          docker push ghcr.io/${{ github.repository_owner }}/exoctl:latest
          docker push ghcr.io/${{ github.repository_owner }}/exoctl:${{ github.sha }}
        else
          docker push ghcr.io/${{ github.repository_owner }}/exoctl:dev
          docker push ghcr.io/${{ github.repository_owner }}/exoctl:dev-${{ github.sha }}
        fi