name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout do reposit처rio principal com suporte a subm처dulos via SSH
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    # 2. Garantir que os subm처dulos est찾o sincronizados e atualizados
    - name: Update Submodules
      run: |
        git submodule sync
        git submodule update --init --recursive

    # 3. Construir a imagem Docker
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag engine-skull:$(date +%s)
