name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout do reposit贸rio principal com subm贸dulos
    - uses: actions/checkout@v4
      with:
        submodules: true

    # 2. Configurar SSH para acessar subm贸dulos privados
    - name: Setup SSH for private repositories
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

    # 3. Atualizar subm贸dulos com acesso SSH
    - name: Update Submodules
      run: |
        git submodule sync
        git submodule update --init --recursive

    # 4. Construir a imagem Docker
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag engine-skull:$(date +%s)
